package com.att.rules;

import java.util.List;
import com.att.dispatch.rule.model.Message;
import com.att.dispatch.rule.model.Analytic;
import com.att.dispatch.rule.process.Compute;
import com.att.dispatch.rule.process.ComputeFactory;

global  com.att.dispatch.rule.process.TurfPool turf_pool

rule "compute and generate turf analytic series"
 when
    $analytic : Analytic( $name: name == "TURF_SERIES")
then
    System.out.println("TURF SERIES");
     List turfs = turf_pool.getAll();
     Compute series = ComputeFactory.newAnalysisSeries($name);
     series.compute(turfs);
     String results = (String)series.getResults();
     //retract($analytic);
     //generate group series and send message
     Message msg = new Message();    
     msg.add("messages:analytics:turf:series",results);
     insert(msg);
end


rule "compute and generate group statistics"
when
    $analytic : Analytic( $name: name == "TURF_GROUP_SERIES")
then
    List turfs = turf_pool.getAll();
    Compute series = ComputeFactory.newAnalysisSeries($name);
    series.compute(turfs);
    String results = (String)series.getResults();
    //$analytic.setResults(results);
    //retract($analytic);
     //generate series and send message
     Message msg = new Message();
     msg.add("messages:analytics:turfs:groups",results);
     insert(msg);
     insert( new Analytic("TURF_SERIES"));
end
