package com.att.rules;

import java.util.ArrayList;
import com.att.dispatch.rule.model.Turf;
import com.att.dispatch.rule.model.Job;
import com.att.dispatch.rule.model.Flag;
import com.att.dispatch.rule.process.RuleHelper;

global  com.att.dispatch.rule.process.JobPool job_pool
global  com.att.dispatch.rule.process.TurfPool turf_pool

rule "a pending job"
  no-loop true
when
   $new_job: Job($turfID : turfID, status =="PENDING" )
then
   String key = $turfID.toString();
   Turf turf = turf_pool.find(key);
   //set the turf name on the job
   $new_job.setTurfName(turf.getName());
   //insert new job into the turf rule to update the turf
   insert($new_job);
   insert(turf);
end


rule "a job is dispatched"
no-loop true
when
  $dispatched_job: Job($turfID : turfID, status == "DISPATCHED")
then
   //find the turf in the datastore
   String key = $turfID.toString(); 
   Turf turf = turf_pool.find(key);
   //set the turf name on the job
   $dispatched_job.setTurfName(turf.getName());
   update($dispatched_job);
   insert(turf);
end


rule "a job is dispatched , start time is set and it is not complete"
   timer(expr: "10s", $duration ; start=$start)
when
   $dispatched_job: Job( $id: id, $turfID : turfID,
                                        status == "DISPATCHED", 
                                        $start : startTime != null, 
                                        $duration : duration !=null )
then
   /** find exist the existing job in  data store and compare with rule's working memory **/
   String key = $turfID.toString();
   String field = $id.toString();
   Job job = job_pool.find($dispatched_job);
   /**  time difference current time to start time in minutes **/
   int difference = RuleHelper.currentTimeDifferent($start);
   if( difference > $duration && 
      ( job!= null && !job.getStatus().equals("COMPLETE") )
     ){     
        Turf turf = turf_pool.find(key);
        //insert into the turf rule to update the turf
        $dispatched_job.setFlag( new Flag("GREEN") );
        update($dispatched_job);
        insert(turf);
    }
    else{
        retract($dispatched_job);
    }

end


rule "a job is complete"
when
   $complete_job: Job($turfID : turfID, status == "COMPLETE")
then
   //find the turf in the datastore 
   String key = $turfID.toString();
   Turf turf = turf_pool.find(key);
   $complete_job.setTurfName(turf.getName());
   insert(turf);
   insert($complete_job);
end