package com.att.rules;

rule "a pending job" extends "new job"
when
   $new_job: Job(status =="PENDING")
then
   System.out.println("job pending"+$new_job);
end

rule "a job is dispatched" extends "new job" 
when
  $dispatched_job: Job(status == "DISPATCHED")
then
   System.out.println("dispatched job"+$dispatched_job); 
end


rule "a job is dispatched, time is set "
   timer(expr: "5s", $period ; start=$start)
when
   $dispatched_job : Job($status: status == "DISPATCHED", $start : startTime != null, 
                         $period : duration !=null, $turdID : turfID )
then
   /**
      find the job in the pool if it is not dispatched , 
      then remove it from working memory
    **/ 
    Job job = job_pool.find($dispatched_job);
    if(job.getStatus().equals($status)){
        //find the turf in the datastore 
    }
    else{
       retract($dispatched_job);
    }
end


rule "a job is complete" extends "new job"
   no-loop true
when
   $complete_job: Job(status == "COMPLETE")
then
   //add or update the job on the
   //find the turf in the datastore 
end
 