package com.att.rules;

import com.att.dispatch.rule.model.Analytic;

/****  PENDING ****/
rule "pending job is added " //extends "status group does not exists"
//activation-group "new job status"
//salience 110
when
    $pending_job: Job($id: id, status == "PENDING")
then    
    System.out.println(" turf job rule sub -no exist ");
    //remove job from the rules working memory
    //retract($pending_job);
end

rule "a pending job is added - #2" extends "status group exists"
//activation-group "existing job status"
//salience 111
when
    $pending_job: Job($id: id, status == "PENDING")
then 
   System.out.println(" turf job rule sub - exist ");
    //remove the facts from working memory
    //retract($pending_job);
end
/*******PENDING JOBS *******/