package com.att.rules;

import com.att.dispatch.rule.model.Turf;
import com.att.dispatch.rule.model.Message;

global  com.att.dispatch.rule.process.BasePool turf_pool

rule "a turf is added" 
no-loop true
when
   $turf : Turf($id: id, active == false)
    Boolean(booleanValue == false) from turf_pool.exists($id.toString())
then
  //update the store and send message
   modify($turf){ setActive(true) }
   Message msg = new Message();
   msg.add("messages:turfs", turf_pool.save($turf));
   insert(msg);
end
