package com.att.dispatch.rule.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dispatch implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long id;
   private java.lang.String name;
   private com.att.dispatch.rule.model.Job currentJob;

   public Dispatch()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public com.att.dispatch.rule.model.Job getCurrentJob()
   {
      return this.currentJob;
   }

   public void setCurrentJob(com.att.dispatch.rule.model.Job currentJob)
   {
      this.currentJob = currentJob;
   }

   public Dispatch(java.lang.Long id, java.lang.String name,
         com.att.dispatch.rule.model.Job currentJob)
   {
      this.id = id;
      this.name = name;
      this.currentJob = currentJob;
   }

}