package com.att.dispatch.rule.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dispatch implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Dispatch() {
    }

}